---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0
  MYSQL_ROOT_PASSWORD: "cm9vdDEyMw=="
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: roboshop
  labels:
    name: mysql
    tier: app
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: rohitsingirikonda/mysql:k8
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    name: mysql
    tier: app
  ports:
  - port: 80
    targetPort: 8080


#echo -n shipping | base64
#echo -n root123 | base64