---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: roboshop
type: Opaque
data:
  username: c2hpcHBpbmc=
  password: c2VjcmV0
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: roboshop
  labels:
    name: mysql
    tier: app
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: rohitsingirikonda/mysql:k8
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretKeyRef:
        name: mysql-secret
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    name: mysql
    tier: app
  ports:
  - port: 80
    targetPort: 8080

