apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: rohitsingirikonda/catalogue:k8
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  namespace: roboshop
spec:
  selector:
    name: catalogue
    tier: app
  ports:
  - port: 8080
    targetPort: 8080

