apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  namespace: roboshop
data:
  MONGO_URL: mongodb://mongodb:80/catalogue
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    name: catalogue
    tier: app
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: rohitsingirikonda/catalogue:k8
    envFrom:
    - configMapRef:
        name: catalogue-config
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
    name: catalogue
    tier: app
  ports:
  - port: 80
    targetPort: 8080

