apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: roboshop
data:
  REDIS_HOST: redis
  MONGO_URL: "mongodb://mongodb:80/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  namespace: roboshop
  labels:
    name: user
    tier: app
spec:
  containers:
  - name: user
    imagePullPolicy: Always
    image: rohitsingirikonda/user:k8
    envFrom:
    - configMapRef:
        name: user-config
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    name: user
    tier: app
  ports:
  - port: 80
    targetPort: 8080

