apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: roboshop
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - name: web
    ImagePullPolicy: Always
    image: rohitsingirikonda/web:k8
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    name: web
    tier: frontend
  ports:
  - port: 80
    targetPort: 80

